#include "SWM341.h"


int main(void)
{	
	SystemInit();
	
	PORT_Init(PORTC, PIN5,  PORTC_PIN5_OPA0_INN,  0);
	PORT_Init(PORTC, PIN8,  PORTC_PIN8_OPA0_INP,  0);
	PORT_Init(PORTC, PIN9,  PORTC_PIN9_OPA0_OUT,  0);
	
	PORT_Init(PORTA, PIN9,  PORTA_PIN9_OPA1_INN,  0);
	PORT_Init(PORTA, PIN11, PORTA_PIN11_OPA1_INP, 0);
	PORT_Init(PORTA, PIN10, PORTA_PIN10_OPA1_OUT, 0);
	
	PORT_Init(PORTC, PIN1,  PORTC_PIN1_OPA2_INN,  0);
	PORT_Init(PORTC, PIN2,  PORTC_PIN2_OPA2_INP,  0);
	PORT_Init(PORTC, PIN3,  PORTC_PIN3_OPA2_OUT,  0);
	
	PORT_Init(PORTA, PIN13, PORTA_PIN13_OPA3_INN, 0);
	PORT_Init(PORTA, PIN14, PORTA_PIN14_OPA3_INP, 0);
	PORT_Init(PORTA, PIN15, PORTA_PIN15_OPA3_OUT, 0);
	
	SYS->OPACR |= (1 << SYS_OPACR_OPA0ON_Pos);
	SYS->OPACR |= (1 << SYS_OPACR_OPA1ON_Pos);
	SYS->OPACR |= (1 << SYS_OPACR_OPA2ON_Pos);
	SYS->OPACR |= (1 << SYS_OPACR_OPA3ON_Pos);
	
	while(1==1)
	{
	}
}
